# -*- coding: utf-8 -*-
"""analyze_statistics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kdQoG_Rqy5FGBqp5i-jzWoqFjJ-CkUi
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import os
from google.colab import drive
import sys
import pickle

drive.mount('/content/drive')
sys.path.append('drive/MyDrive/frisbee_analysis/wall_city_2025')
from plotting import draw_field

pd.options.display.max_columns = None

DATA_DIRECTORY = "frisbee_analysis/wall_city_2025/data"
GAMES = {
    "Heidees 2025-05-18_20-38-33": "Heidees - Tom's Tourney",
    "Italy Masters 2025-05-25_11-05-03": "Italy Masters - Tom's Tourney",
    "Tchac 2025-05-25_17-52-13": "Tchac - Tom's Tourney",
    "FAB 2025-05-29_10-05-10": "FAB - Tom's Tourney",
    "IznoGood 2025-05-03_13-15-00": "Iznogood - Tom's Tourney",
    "Tchac Final 2025-06-01_14-30-00": "Tchac Final - Elite Invite",
    "Tchac 2025-05-30_17-24-00": "Tchac Pool - Elite Invite",
    "Grut 2025-05-31_17-45-00": "Grut - Elite Invite",
    "Chevron Action Flash   2025-05-31_12-30-00": "Chevy - Elite Invite",
    "FrankN 2025-07-04_10-40-00": "Frank N - DM 1",
    "Heidees Summer Inv 2025-05-02_10-52-50": "Heidees - Summer Invite",
    "Grut 2025-08-03_15-00-34": "Grut - Summer Invite",
    "Heidees 2025-09-07_14-00-22": "Heidees - Berlin Invite",
    "3SB 2025-09-07_12-00-12": "3SB - Berlin Invite",
}
MODEL_DIRECTORY = 'frisbee_analysis/models/'
POSSESSION_MODEL = 'linear_gp.p'
POINT_MODEL = 'linear_point_scored.p'

NAME_MAPPINGS = {
    '09 Kryz Zajac': '09 Zajac',
    '02 Ondrej Rydlo': '02 Cego',
    '94 Jannis Wenderholm': '94 Jannis',
    '17 Steffen Linnemanstons': '17 Steffen',
    '03 Andres Brand': '03 Andres',
    '24 Philipp Steffan': '24 Philipp',
    '33 Ned Garvey': '33 Ned',
    '65 Ron Doempke': '65 Ron',
    '99 Bruno Jorginsons': '99 Bruno',
    '29 Ruben Ahlers': '29 Ruben',
    '21 Paul Herkens ': '21 Business',
    '13 Hartley Greenwald': '13 Hartley',
    '13 Hartley ': '13 Hartley',
    '13  Hartley': '13 Hartley',
    '47 Conrad Schlor': '47 Conrad',
    '20 Phil Kaye': '20 Phil',
    '77 David Metzger': '77 David',
    '10 Leo Eichler': '10 Leo',
    '18 Thorben Haag': '18 Thorben',
    '36 Yannick Marburg': '36 Yannick',
    '25 Vlad Basov': '25 Vlad',
    '34 Stefan Kuhn': '34 Icey',
    '14 Robin Chan': '44 Robin'
}

from ast import Pass
class StatsBank:
  def __init__(self, directory, games=[]):
    self.data_directory = os.path.join('/content/drive/MyDrive', DATA_DIRECTORY)
    self.model_directory = os.path.join('/content/drive/MyDrive', MODEL_DIRECTORY)
    self._load_possession_model()
    self._load_point_model()
    self.aggregated_player_stats_df = pd.DataFrame() # full aggregated stats over all games
    self.game_stats_df = pd.DataFrame()
    self.point_stats_df = pd.DataFrame()
    self.games = games

  def load_data(self):
    """Load up the data. We'll put everything in dicts of dataframes to begin with
       and then aggregate into the final dataframes,"""
    self.player_stats_dfs = {}
    self.passes_dfs = {}
    self.possessions_dfs = {}
    self.points_dfs = {}
    self.player_points_dfs = {}
    self.blocks_dfs = {}
    for game_id, game_name in self.games.items():
      self.player_stats_dfs[game_id] = pd.read_csv(os.path.join(self.data_directory, f"Player Stats vs. {game_id}.csv"))
      self.passes_dfs[game_id] = pd.read_csv(os.path.join(self.data_directory, f"Passes vs. {game_id}.csv"))
      self.possessions_dfs[game_id] = pd.read_csv(os.path.join(self.data_directory, f"Possessions vs. {game_id}.csv"))
      self.points_dfs[game_id] = pd.read_csv(os.path.join(self.data_directory, f"Points vs. {game_id}.csv"))
      try:
        self.blocks_dfs[game_id] = pd.read_csv(os.path.join(self.data_directory, f"Defensive Blocks vs. {game_id}.csv"))
      except:
        self.blocks_dfs[game_id] = pd.DataFrame()
        print(f"No defensive blocks data for {game_id}")

      self.passes_dfs[game_id]['game'] = game_name
      self.possessions_dfs[game_id]['game'] = game_name
      self.points_dfs[game_id]['game'] = game_name
      self.blocks_dfs[game_id]['game'] = game_name

    assert len(self.player_stats_dfs) == len(self.games)
    assert len(self.passes_dfs) == len(self.games)
    assert len(self.possessions_dfs) == len(self.games)
    assert len(self.points_dfs) == len(self.games)

  def prepare_data(self):
    self.load_data()
    self._rename_columns()
    self._fix_player_names()
    self._transform_pass_stats()

  def _rename_columns(self):
    """Get more consistent and easier to use column names"""

    for game_id, df in self.passes_dfs.items():
      df.rename({
          'Start X (0 -> 1 = left sideline -> right sideline)': 'start_x',
          'Start Y (0 -> 1 = back of opponent endzone -> back of own endzone)': 'start_y',
          'End X (0 -> 1 = left sideline -> right sideline)': 'end_x',
          'End Y (0 -> 1 = back of opponent endzone -> back of own endzone)': 'end_y'
      }, axis=1, inplace=True)

    for game_id, df in self.possessions_dfs.items():
      df.rename({
          'Start X (0 -> 1 = left sideline -> right sideline)': 'start_x',
          'Start Y (0 -> 1 = back of opponent endzone -> back of own endzone)': 'start_y',
          'End X (0 -> 1 = left sideline -> right sideline)': 'end_x',
          'End Y (0 -> 1 = back of opponent endzone -> back of own endzone)': 'end_y'
      }, axis=1, inplace=True)

    for game_id in self.games.keys():
      self.passes_dfs[game_id].columns = self._clean_column_names(self.passes_dfs[game_id].columns)
      self.possessions_dfs[game_id].columns = self._clean_column_names(self.possessions_dfs[game_id].columns)
      self.points_dfs[game_id].columns = self._clean_column_names(self.points_dfs[game_id].columns)
      self.player_stats_dfs[game_id].columns = self._clean_column_names(self.player_stats_dfs[game_id].columns)
      self.blocks_dfs[game_id].columns = self._clean_column_names(self.blocks_dfs[game_id].columns)

  @staticmethod
  def _clean_column_names(columns):
    """Get more consistent and easier to use column names"""
    return columns.str.lower().str.replace(' ', '_').str.replace('?', '').str.replace("'", "")

  def _fix_player_names(self):
    """Correct inconsitencies in player names"""
    for game_id, df in self.passes_dfs.items():
      df['thrower'] = df['thrower'].replace(NAME_MAPPINGS)
      df['receiver'] = df['receiver'].replace(NAME_MAPPINGS)

    # do the same in the player stats dataframe
    for game_id, df in self.player_stats_dfs.items():
      df['player'] = df['player'].replace(NAME_MAPPINGS)

    for game_id, df in self.blocks_dfs.items():
      if "player" in df.columns: # are there any blocks for this game?
        df['player'] = df['player'].replace(NAME_MAPPINGS)

  def _transform_pass_stats(self):
    """Convert the passing numbers to terms that we're interested in. i.e. location -> distance to endzone"""
    for game_id, df in self.passes_dfs.items():
      df['dist_to_endzone_end'] = df['end_y']*100-18
      df['dist_to_endzone_start'] = df['start_y']*100-18
      df['dist_to_endzone_end_capped'] = df['dist_to_endzone_end'].clip(lower=0)
      df['start_x_m'] = df['start_x']*36
      df['end_x_m'] = df['end_x']*36
      df['dist_from_middle_start'] = abs(18-df['start_x_m'])
      df['dist_from_middle_end'] = abs(18-df['end_x_m'])
      df['dist_from_sideline_start'] = abs( 18-df['dist_from_middle_start'])
      df['dist_from_sideline_end'] = abs(18-df['dist_from_middle_end'])
      df['dist_from_middle_diff'] = df['dist_from_middle_start'] - df['dist_from_middle_end']
      df['dist_to_endzone_diff'] = df['dist_to_endzone_start'] - df['dist_to_endzone_end_capped']

      assert (df.loc[df['assist']==1, 'dist_to_endzone_end'] < 0).all()
      assert (df.loc[:,'dist_to_endzone_start'] >= 0).all()
      assert (df.loc[:,'dist_from_sideline_start'] <= 18).all()
      assert (df.loc[:,'dist_from_sideline_start'] >= 0).all()

    for game_id, df in self.possessions_dfs.items():
      df['dist_to_endzone_start'] = df['start_y']*100-18
      df['start_x_m'] = df['start_x']*36
      df['dist_from_middle_start'] = abs(18-df['start_x_m'])
      df['dist_from_sideline_start'] = abs( 18-df['dist_from_middle_start'])

  def _transform_points_played(self):
    """Make data frames with players and each point they played on the rows."""
    for game_id, df in self.player_stats_dfs.items():
        # Ensure 'points_played' is treated as a string before splitting
        df['points_played'] = df['points_played'].astype(str)
        # Split the 'points_played' string and explode into new rows
        transformed_df = df.assign(points_played=df['points_played'].str.split(',')).explode('points_played')[['player', 'points_played']]
        # Convert the exploded 'points_played' column to integer
        transformed_df['points_played'] = pd.to_numeric(transformed_df['points_played'], errors='coerce').astype('Int64')
        # Remove rows where points_played is NaN (from splitting empty strings etc.)
        transformed_df.dropna(subset=['points_played'], inplace=True)
        self.player_points_dfs[game_id] = transformed_df

  def compute_all_stats(self):
    self._transform_points_played()
    self._compute_game_stats()
    self._compute_scoring_probabilities()
    self._compute_gpa()
    self._compute_player_game_stats()
    self.aggregated_player_stats_df = self._compute_player_stats(self.aggregated_player_stats_df)
    self.game_player_stats_df = self._compute_player_stats(self.game_player_stats_df)

  def _compute_scoring_probabilities(self):
    """Use the possession model to compute the starting and ending probabilites of scoring for each pass."""
    for game_id, df in self.passes_dfs.items():
      df['scoring_prob_start'] = self.point_model.predict(sm.add_constant(df[['dist_to_endzone_start', 'dist_from_sideline_start']]))
      df['scoring_prob_end'] = self.point_model.predict(sm.add_constant(df[['dist_to_endzone_end_capped', 'dist_from_sideline_end']]))
      df['scoring_prob_end'] = df.apply(lambda x: 1 if x['assist']==1 else x['scoring_prob_end'], axis=1)
      df['scoring_prob_end'] = df.apply(lambda x: 0 if x['turnover']==1 else x['scoring_prob_end'], axis=1)

      # compute opponents scoring probability
      df['opp_dist_to_endzone_end_capped'] = 70-df['dist_to_endzone_end_capped']
      df['scoring_prob_end_opp'] = self.point_model.predict(sm.add_constant(df[['opp_dist_to_endzone_end_capped', 'dist_from_sideline_end']]))

    for game_id, df in self.possessions_dfs.items():
      df['scoring_prob_start'] = self.possession_model.predict(sm.add_constant(df[['dist_to_endzone_start', 'dist_from_sideline_start']]))

  def _compute_gpa(self):
    """Compute the goal probability added"""
    for game_id, df in self.passes_dfs.items():
      df['game_efficiency'] = self.get_game_efficiency(game_id)
      df['gpa'] = df['scoring_prob_end'] - df['scoring_prob_start']
      df['gpa'] = df.apply(self._make_turnover_correction, axis=1)
      df['thrower_gpa'] = df.apply(lambda x: self._assign_credit(x, 'thrower'), axis=1)
      df['receiver_gpa'] = df.apply(lambda x: self._assign_credit(x, 'receiver'), axis=1)

  def _compute_max_gpa_all(self):
    """For each player, compute the maximum GPA which you could have had."""
    max_gpas_df = pd.DataFrame()
    for game_id, df in self.possessions_dfs.items():
      player_possessions_df = pd.merge(self.player_points_dfs[game_id], df, left_on='points_played', right_on='point', how='left')
      result = (player_possessions_df.groupby('player')['scoring_prob_start'].sum()/2).reset_index() # divide by 2 because you can't do it all yourself
      result['game'] = GAMES[game_id]
      max_gpas_df = pd.concat([max_gpas_df, result], ignore_index=True)
    max_gpas_df.columns = ['player', 'game', 'max_gpa']
    return max_gpas_df

  def _compute_max_gpa_game(self, game_id):
      """For each player, compute the maximum GPA which you could have had for a single game."""
      possession_df = self.possessions_dfs[game_id]
      player_possessions_df = pd.merge(self.player_points_dfs[game_id], possession_df, left_on='points_played', right_on='point', how='left')
      result = (player_possessions_df.groupby('player')['scoring_prob_start'].sum()/2).reset_index() # divide by 2 because you can't do it all yourself
      result.columns = ['player', 'max_gpa']
      return result

  def _compute_player_game_stats(self):
      """Aggregate individual player stats across all games."""
      all_passes = []
      # make a dataframe which will have stats broken out on a game level
      self.game_player_stats_df = pd.DataFrame()
      for game_id, df in self.passes_dfs.items():
          offensive_game_stats = self._aggregate_offensive_player_stats(df, game=GAMES[game_id])
          defensive_game_stats = self._aggregate_defensive_player_stats(game_id=game_id)
          if defensive_game_stats is not None:
            game_stats = offensive_game_stats.merge(defensive_game_stats, on="player", how="left")
          else:
            game_stats = offensive_game_stats

          self.game_player_stats_df = pd.concat([self.game_player_stats_df, game_stats])

      self.aggregated_player_stats_df = self._aggregate_player_stats_all_games(self.game_player_stats_df)

  def _aggregate_defensive_player_stats(self, game_id=None):

    def _compute_defensive_blocks(self, game_id):
      blocks_df = self.blocks_dfs[game_id]
      # count up the blocks for each player
      blocks_df = blocks_df.groupby("player").count()

      # a row only gets created here when there's a block, so you can use any column you want as the blocks column
      blocks_df.rename(columns={"created": "blocks"}, inplace=True)

      # fill in all other players who played this game with 0 blocks
      all_players = self.player_stats_dfs[game_id]['player'].values
      blocks_df = blocks_df.reindex(all_players, fill_value=0)
      blocks_df.reset_index(inplace=True)
      return blocks_df[['player', 'blocks']]

    def _compute_defensive_gpa(self, blocks_df, game_id):
      blocks_df['game_efficiency'] = self.get_game_efficiency(game_id)
      blocks_df['total_defensive_gpa'] = blocks_df['blocks'] * blocks_df['game_efficiency']
      return blocks_df

    if len(self.blocks_dfs[game_id]) == 0:
      return None

    blocks_df = _compute_defensive_blocks(self, game_id)
    blocks_df = _compute_defensive_gpa(self, blocks_df, game_id)
    return blocks_df

  def _aggregate_offensive_player_stats(self, passes_df, game=None):
    """Given an aggregated player dataframe, compute some extra stats."""

    # Compute adjusted turnovers based on blame
    passes_df['thrower_turnover_credit'] = passes_df.apply(lambda row: (
        0.5 if row['thrower_error'] == 1 and row['receiver_error'] == 1 else
        1 if row['thrower_error'] == 1 else
        0
    ) if row['turnover'] == 1 else 0, axis=1)
    passes_df['receiver_turnover_credit'] = passes_df.apply(lambda row: (
        0.5 if row['thrower_error'] == 1 and row['receiver_error'] == 1 else
        1 if row['receiver_error'] == 1 else
        0
    ) if row['turnover'] == 1 else 0, axis=1)

    # start with all players as an axis just in case some players don't have a pass in a game
    stats_df = pd.DataFrame(index=self.get_players())

    # ----- Thrower Stats -----
    completed_thrower_df = passes_df.query('turnover==0').groupby('thrower').agg({
        'assist': 'sum',
        'secondary_assist': 'sum',
        'huck': 'sum',
        'swing': 'sum',
        'dump': 'sum',
        'dist_to_endzone_diff': 'sum',
        'dist_from_middle_diff': 'sum',
        'thrower': 'count',
        'thrower_gpa': 'sum'
    }).rename_axis('player') \
      .rename({
          'dist_to_endzone_diff': 'throwing_meters_gained',
          'dist_from_middle_diff': 'throwing_centering_meters_gained',
          'assist': 'assists',
          'huck': 'hucks_completed',
          'secondary_assist': 'secondary_assists',
          'swing': 'swings',
          'dump': 'dumps',
          'thrower': 'completions',
          'thrower_gpa': 'thrower_gpa_no_turns'
      }, axis='columns').reset_index()

    thrower_df = passes_df.groupby('thrower').agg({
        'thrower_turnover_credit': 'sum',
        'thrower_gpa': 'sum',
        'thrower': 'count',
        'huck': 'sum',
    }).rename_axis('player').rename({
        'thrower_turnover_credit': 'turnover_thrown',
        'thrower': 'throws',
        'huck': 'hucks_thrown',
    }, axis='columns').reset_index()


    thrower_df = pd.merge(thrower_df, completed_thrower_df, on='player', how='outer')
    thrower_df.fillna(0, inplace=True)

    # ----- Receiver Stats -----
    completed_receiver_df = passes_df.query('turnover==0').groupby('receiver').agg({
        'assist': 'sum',
        'huck': 'sum',
        'receiver': 'count',
        'dist_to_endzone_diff': 'sum',
        'dist_from_middle_diff': 'sum',
        'receiver_gpa': 'sum'
    }).rename_axis('player')\
      .rename({
          'dist_to_endzone_diff': 'receiving_meters_gained',
          'dist_from_middle_diff': 'receiving_centering_meters_gained',
          'receiver': 'catches',
          'assist': 'goals',
          'huck': 'hucks_received',
          'receiver_gpa': 'receiver_gpa_no_turns'
      }, axis='columns').reset_index()

    receiver_df = passes_df.groupby('receiver').agg({
        'receiver_turnover_credit': 'sum',
        'receiver_gpa': 'sum',
    }).rename_axis('player').rename({
        'receiver_turnover_credit': 'receiver_turnovers'
    }, axis='columns').reset_index()

    receiver_df = pd.merge(receiver_df, completed_receiver_df, on='player', how='outer')
    receiver_df.fillna(0, inplace=True)

    # ----- Merge Thrower and Receiver Stats -----
    stats_df = pd.merge(stats_df, thrower_df, left_index=True, right_on='player', how='outer')
    stats_df = pd.merge(stats_df, receiver_df, on='player', how='outer', suffixes=('_as_thrower', '_as_receiver'))
    stats_df.fillna(0, inplace=True)

    # Add total GPA, total turnovers, touches
    stats_df['total_offensive_gpa'] = stats_df['thrower_gpa'] + stats_df['receiver_gpa']
    stats_df['total_offensive_gpa_no_turns'] = stats_df['thrower_gpa_no_turns'] + stats_df['receiver_gpa_no_turns']
    stats_df['total_turnovers'] = stats_df['turnover_thrown'] + stats_df['receiver_turnovers']
    stats_df['touches'] = stats_df['throws'] + stats_df['goals']
    stats_df['game'] = game

    # compute the max GPA for the game and then join
    game_id = {v: k for k, v in GAMES.items()}[game]
    max_gpas_df = self._compute_max_gpa_game(game_id=game_id)
    stats_df = stats_df.merge(max_gpas_df, on='player', how='left')

    return stats_df

  def _aggregate_player_stats_all_games(self, df):
    """Take the individual games and aggregate them together."""
    result_df = df.groupby('player').sum().reset_index()
    # compute the number of games
    result_df['games'] = df.groupby('player')['game'].nunique().values
    return result_df

  def _assign_credit(self, row, thrower_or_receiver):
    if thrower_or_receiver == 'thrower':
      if row['thrower_error']==1 & row['receiver_error']==1:
        return row['gpa']/2
      elif row['thrower_error']==1:
        return row['gpa']
      elif row['receiver_error']==1:
        return 0
      else:
        return row['gpa']/2
    elif thrower_or_receiver == 'receiver':
      if row['thrower_error']==1 & row['receiver_error']==1:
        return row['gpa']/2
      if row['receiver_error']==1:
        return row['gpa']
      elif row['thrower_error']==1:
        return 0
      else:
        return row['gpa']/2

  def _load_possession_model(self):
    with open(os.path.join(self.model_directory, POSSESSION_MODEL), 'rb') as f:
      self.possession_model = pickle.load(f)

  def _load_point_model(self):
    with open(os.path.join(self.model_directory, POINT_MODEL), 'rb') as f:
      self.point_model = pickle.load(f)

  # def _make_turnover_correction(self, row):
  #   """
  #   Compute the GPA of a turnover. Just use the negative game efficiency for now.
  #   Essentially this is the likelihood of either team scoring, so it's a rough
  #   approximation of the lost value of the turnover.

  #   If the throw wasn't a turnover, then the value stays the same.
  #   """
  #   return -row['game_efficiency'] if row['turnover']==1 else row['gpa']

  def _make_turnover_correction(self, row):
    """
    Compute the GPA of a turnover. Just use the negative game efficiency for now.
    Essentially this is the likelihood of either team scoring, so it's a rough
    approximation of the lost value of the turnover.

    If the throw wasn't a turnover, then the value stays the same.
    """
    return (1 - row['scoring_prob_end_opp']) - row['scoring_prob_start'] if row['turnover']==1 else row['gpa']

  def get_game_efficiency(self, game_id):
    """Return the overall scoring efficiency from a certain game."""
    return self.game_stats_df.loc[self.game_stats_df['game_id']==game_id, 'combined_scoring_efficiency'].values[0]

  def get_players(self):
    """Get a list of all the players."""
    players = []
    for game_id, df in self.player_stats_dfs.items():
      players += list(df['player'].unique())

    return list(set(players))

  def _compute_game_stats(self):
    """Compute the game-level stats, which we'll also need to compute all the player level stats."""
    for game_id, name in self.games.items():
      points_df = self.points_dfs[game_id]
      passes_df = self.passes_dfs[game_id]
      possessions_df = self.possessions_dfs[game_id]
      game_stats = {}
      game_stats['game_id'] = game_id
      game_stats['game_name'] = name
      points_df['opponent_possessions'] = points_df.apply(self._compute_opponent_possessions, axis=1)
      game_stats['possessions'] = points_df['possessions'].sum()
      game_stats['opponent_possessions'] = points_df['opponent_possessions'].sum()
      game_stats['passes'] = points_df['passes'].sum()
      game_stats['points'] = points_df['point'].max()-1. # there's an extra row in the df for the final score
      game_stats['our_score'], game_stats['opponent_score'] = self._get_final_score(points_df)
      game_stats['our_scoring_efficiency'] = game_stats['our_score']/game_stats['possessions']
      game_stats['opponent_scoring_efficiency'] = game_stats['opponent_score']/game_stats['opponent_possessions']
      game_stats['combined_scoring_efficiency'] = (game_stats['our_score'] + game_stats['opponent_score'])/(game_stats['opponent_possessions'] + game_stats['possessions'])
      self.game_stats_df = pd.concat([self.game_stats_df, pd.DataFrame([game_stats])], ignore_index=True)

  def _compute_player_stats(self, df):
      """Given an aggregated player dataframe, compute some extra stats."""
      # normalize the gpa
      df['adjusted_offensive_gpa'] = df['total_offensive_gpa']/(df['max_gpa'])
      df['adjusted_thrower_gpa'] = df['thrower_gpa']/(df['max_gpa'])
      df['adjusted_receiver_gpa'] = df['receiver_gpa']/(df['max_gpa'])
      df['total_gpa'] = df['total_offensive_gpa'] + df['total_defensive_gpa']

      # traditional +/-
      df['off. plus/minus'] = df['goals'] + df['assists'] - df['total_turnovers']
      df['off. real plus/minus'] = (df['goals'] + df['assists'])/2 - df['total_turnovers']

      # effective throwing and recieving meters, taking into account lateral movement
      vert_coef = SB.possession_model.params.values[1]
      horz_coef = SB.possession_model.params.values[2]
      df['gpa_vert_throwing'] = df['throwing_meters_gained']*-vert_coef
      df['gpa_horz_throwing'] = df['throwing_centering_meters_gained']*horz_coef
      df['gpa_total_throwing'] = df['gpa_vert_throwing'] + df['gpa_horz_throwing']
      df['gpa_vert_receiving'] = df['receiving_meters_gained']*-vert_coef
      df['gpa_horz_receiving'] = df['receiving_centering_meters_gained']*-horz_coef
      df['gpa_total_receiving'] = df['gpa_vert_receiving'] + df['gpa_horz_receiving']

      # completion percentage stats
      df['completion_percentage'] = df['completions']/df['throws']

      df = self.reorder_player_stat_columns(df)
      return df

  @staticmethod
  def _compute_opponent_possessions(point_row):
    """Function to compute the total number of possessions per point, given our data.

       If we started on offense AND scored, we ended up with one more possession.
       If we started on offense XOR scored, we ended up with the same number of possessions.
       If we did neither, we had one fewer possession.
    """
    a = point_row['scored'] + point_row['started_on_offense']
    return point_row['possessions'] - (a-1)

  @staticmethod
  def _get_final_score(points_df):
    """Get the final score from the points dataframe."""
    last_row = points_df.iloc[-1]
    return last_row['our_score_at_pull'], last_row['opponents_score_at_pull']

  def compute_game_efficiency(self):
    pass

  def plot_events(self, event, thrower=None, receiver=None, games=[], draw_arrows=False):
      """Make a field plot of all the turnover passes for a given player.
      Draws the ultimate frisbee field and turnover passes with a line and an x at the end.
      Allows an optional parameter to show only turnovers from a single player.

      Args:
          player (str, optional): The player name to filter turnovers. Defaults to None.
          games (list, optional): List of game IDs to include. Defaults to all loaded games.
      """
      if not games:
        games = self.games.keys()

      ax = draw_field()

      assert not (thrower and receiver), "Cannot specify the thrower and receiver"

      if thrower or receiver:
        player = thrower or receiver
        ax.set_title(f"{event}s for {player}")
      else:
        player = None
        ax.set_title(f"{event}s")

      for game_id in games:
        if game_id in self.passes_dfs:
          passes_df = self.passes_dfs[game_id].copy()
          if event=='passes':
            events_df = passes_df
          else:
            events_df = passes_df[passes_df[event] == 1]

          if player:
            if thrower:
              events_df = events_df[events_df['thrower'] == player]
            elif receiver:
              events_df = events_df[events_df['receiver'] == player]

            if len(events_df)==0:
              print(f"No {event} found for player '{player}' in game '{game_id}'.")
              continue

          for index, row in events_df.iterrows():
            # dist_to_endzone_start and dist_to_endzone_end are relative to the far endzone.
            # Since we inverted the y-axis, a higher 'dist_to_endzone' value will be higher on the plot.
            start_y = row['dist_to_endzone_start']
            end_y = row['dist_to_endzone_end']
            start_x = row['start_x_m']
            end_x = row['end_x_m']

            if draw_arrows:
              # Draw the pass line
              ax.plot([start_x, end_x], [start_y, end_y], color='red', linestyle='-', linewidth=1)
              # Draw end point (x)
              ax.plot(end_x, end_y, 'x', color='red', markersize=6, markeredgewidth=1.5)
            # Draw start point (circle)
            ax.plot(start_x, start_y, 'o', color='blue', markersize=4)
        else:
          print(f"Warning: Game ID '{game_id}' not found in loaded passes data.")


      plt.show()

  def plot_assists(self, thrower=None, receiver=None, games=[], draw_arrows=False):
      self.plot_events(
          'assits',
          thrower=thrower,
          receiver=receiver,
          games=games,
          draw_arrows=draw_arrows
      )
  def plot_turnovers(self, thrower=None, receiver=None, games=[], draw_arrows=False):
      self.plot_events(
          'turnover',
          thrower=thrower,
          receiver=receiver,
          games=games,
          draw_arrows=draw_arrows
      )
  def plot_passes(self, thrower=None, receiver=None, games=[], draw_arrows=False):
      self.plot_events(
          'passes',
          thrower=thrower,
          receiver=receiver,
          games=games,
          draw_arrows=draw_arrows
      )
  def plot_hucks(self, thrower=None, receiver=None, games=[], draw_arrows=False):
      self.plot_events(
          'huck',
          thrower=thrower,
          receiver=receiver,
          games=games,
          draw_arrows=draw_arrows
      )



  def reorder_player_stat_columns(self, df):
    """Return the dataframes with the stats in the order that are easiest to read."""
    desired_order = [
        'player',
        'games',
        'total_gpa',
        'total_offensive_gpa',
        'total_defensive_gpa',
        'adjusted_offensive_gpa',
        'adjusted_thrower_gpa',
        'adjusted_receiver_gpa',
        'touches',
        'throws',
        'completions',
        'completion_percentage',
        'blocks',
        'goals',
        'assists',
        'total_turnovers',
        'off. plus/minus',
        'off. real plus/minus',
        'total_offensive_gpa_no_turns',
        'max_gpa',
        'turnover_thrown',
        'thrower_gpa',
        'hucks_thrown',
        'secondary_assists',
        'hucks_completed',
        'swings',
        'dumps',
        'throwing_meters_gained',
        'throwing_centering_meters_gained',
        'thrower_gpa_no_turns',
        'receiver_turnovers',
        'receiver_gpa',
        'hucks_received',
        'catches',
        'receiving_meters_gained',
        'receiving_centering_meters_gained',
        'receiver_gpa_no_turns',
        'gpa_vert_throwing',
        'gpa_horz_throwing',
        'gpa_total_throwing',
        'gpa_vert_receiving',
        'gpa_horz_receiving',
        'gpa_total_receiving',
        'game_efficiency',
        'game', # Optional column
    ]

    # Keep only columns that are in the DataFrame
    ordered_columns = [col for col in desired_order if col in df.columns]

    return df[ordered_columns]

  def export_stats(self):
    """Export all the computed stats to their locations."""
    output_directory = os.path.join(self.data_directory, 'processed')
    for game_id, df in self.player_stats_dfs.items():
      game_name = self.games[game_id]
      df = self.game_player_stats_df.query('game == @game_name')
      df.to_csv(os.path.join(output_directory, f'{game_name}_player_stats.csv'))

    self.aggregated_player_stats_df.to_csv(os.path.join(output_directory, 'aggregated_player_stats.csv'))
    self.game_stats_df.to_csv(os.path.join(output_directory, 'game_stats.csv'))

import matplotlib.pyplot as plt

class Plotting:
  def __init__():
    pass

  def draw_field():
    plt.figure(figsize=(20, 8))
    ax = plt.gca()

    # Draw field
    # Assuming field width is 36m
    field_width = 36
    # Assuming distance between endzone lines is 46m (64m total field length - 2 * 9m endzones)
    # Reversing the y-axis so attacking endzone (dist_to_endzone=64) is at the top
    # The coordinate 0 corresponds to the far endzone line (dist_to_endzone=0)
    # The coordinate 64 corresponds to the near endzone line (dist_to_endzone=64)
    total_field_length = 100
    central_zone_length = 64

    ax.plot([0, field_width], [0, 0], color='black') # Far endzone line (dist_to_endzone=0)
    ax.plot([0, field_width], [-18, -18], color='black') # back line (dist_to_endzone=0)
    ax.plot([0, field_width], [central_zone_length, central_zone_length], color='black') # Near endzone line (dist_to_endzone=64)
    ax.plot([0, field_width], [total_field_length-18, total_field_length-18], color='black') # back line
    ax.plot([0, 0], [-18, total_field_length-18], color='black') # Left sideline
    ax.plot([field_width, field_width], [-18, total_field_length-18], color='black') # Right sideline

    # Draw brick marks as dots in the middle of the field
    # Far brick mark (18m from far endzone)
    ax.plot([field_width/2, field_width/2], [18, 18], color='black', linestyle='--', marker='o', markersize=5)
    ax.plot([field_width/2, field_width/2], [central_zone_length-18, central_zone_length-18], color='black', linestyle='--', marker='o', markersize=5)

    # Draw dotted midline
    ax.plot([0, field_width], [central_zone_length/2, central_zone_length/2], color='black', linestyle='--')

    # Set plot limits and labels
    ax.set_xlim(-5, field_width + 5)
    ax.set_ylim(-20, total_field_length-18 + 5)
    ax.set_aspect('equal', adjustable='box')
    ax.set_xlabel('Field Width (m)')
    ax.set_ylabel('Distance from Far Endzone (m)') # Adjusted label based on axis direction

    # Flip the y-axis so the near endzone (dist_to_endzone=64) is at the top
    # This corresponds to the 'dist_to_endzone' values from the dataframe
    ax.invert_yaxis()
    return ax

SB = StatsBank(DATA_DIRECTORY, GAMES)
SB.prepare_data()
SB.compute_all_stats()
SB.export_stats()

from copy import deepcopy
SB_old = deepcopy(SB)

SB.passes_dfs.keys()

SB.passes_dfs["Tchac 2025-05-30_17-24-00"].query('turnover == 1')

SB.aggregated_player_stats_df.sort_values(['adjusted_offensive_gpa'], ascending=False)

old_gpas = SB_old.aggregated_player_stats_df[['player', 'total_offensive_gpa']]
new_gpas = SB.aggregated_player_stats_df[['player', 'total_offensive_gpa']]
all_gpas = pd.merge(old_gpas, new_gpas, on='player', suffixes=('_old', '_new'))
all_gpas['gpa_diff'] = (all_gpas['total_offensive_gpa_new'] - all_gpas['total_offensive_gpa_old'])
all_gpas.sort_values('gpa_diff', ascending=False)

"""# Defensive Efficiency

Analyze our player's efficiency of getting turnovers when they're on the line, and the efficiency of our offense.
"""

SB.player_points_dfs['Tchac 2025-05-30_17-24-00']

SB.player_points_dfs['Tchac 2025-05-30_17-24-00']

all_pp = pd.DataFrame()
for game_id, game_name in SB.games.items():
  print(game_name)
  points_df = SB.points_dfs[game_id]
  player_points_df = SB.player_points_dfs[game_id].merge(points_df, right_on='point', left_on='points_played')
  player_points_df['turned_opp'] = (player_points_df['started_on_offense']==0) & (player_points_df['possessions']>0)
  player_points_df['game'] = game_name
  player_points_df['game_id'] = game_id
  all_pp = pd.concat([player_points_df, all_pp])

d_points = all_pp.query('started_on_offense==0')

g = d_points.groupby('player')
stats = g.agg({
    'point': 'count',
    'turned_opp': 'mean',
    'possessions': 'sum',
    'scored': 'sum',
    'game': 'nunique'
})
stats = stats.rename(columns={
    'point': 'total_points',
    'turned_opp': 'turn_rate',
    'scored': 'breaks',
    'game': 'games'
}).reset_index()
stats['scoring_efficiency'] = stats['breaks']/stats['possessions']
stats['break_efficiency'] = stats['breaks']/stats['total_points']

stats.sort_values('turn rate', ascending=False)

stats.sort_values('scoring_efficiency', ascending=False)

stats.sort_values('break_efficiency', ascending=False)

d_points['turned_opp'] = d_points['turned_opp'].astype(int)
d_points = d_points.query('turned_opp == 1')
labels = d_points.groupby(['game', 'points_played'])[['turned_opp', 'scored']].max().reset_index()

d_points['played'] = 1
X = d_points.pivot(index=['game', 'points_played'], columns='player', values='played').fillna(0)
X = X.reset_index().drop(['game', 'points_played'], axis=1)
y = labels['scored']

import statsmodels.api as sm
X = sm.add_constant(X)
model = sm.Logit(y, X)
result = model.fit()

result.summary()

from sklearn.linear_model import LogisticRegression

# Regularized logistic regression
model = LogisticRegression(
    penalty="l2",      # ridge penalty
    C=1.0,             # smaller = stronger regularization
    solver="liblinear" # good for small data
)
model.fit(X, y)

coefs = pd.Series(model.coef_[0], index=X.columns)
print(coefs.sort_values())

import numpy as np

def permutation_test(model, X, y, n_perms=1000):
    model.fit(X, y)
    orig_coefs = model.coef_[0].copy()

    perm_coefs = np.zeros((n_perms, X.shape[1]))
    for i in range(n_perms):
        y_perm = np.random.permutation(y)
        model.fit(X, y_perm)
        perm_coefs[i] = model.coef_[0]

    pvals = np.mean(np.abs(perm_coefs) >= np.abs(orig_coefs), axis=0)
    return orig_coefs, pvals

model = LogisticRegression(penalty="l2", C=1.0, solver="liblinear")
coefs, pvals = permutation_test(model, X, y)

results = pd.DataFrame({"coef": coefs, "pval": pvals}, index=X.columns)
print(results.sort_values("coef"))

def bootstrap_ci(model, X, y, n_boot=1000, ci=95):
    coefs = []
    n = len(y)
    for _ in range(n_boot):
        idx = np.random.choice(np.arange(n), size=n, replace=True)
        model.fit(X.iloc[idx], y.iloc[idx])
        coefs.append(model.coef_[0])
    coefs = np.array(coefs)

    lower = np.percentile(coefs, (100-ci)/2, axis=0)
    upper = np.percentile(coefs, 100-(100-ci)/2, axis=0)
    return lower, upper

lower, upper = bootstrap_ci(model, X, y)
intervals = pd.DataFrame({"coef": coefs, "lower": lower, "upper": upper}, index=X.columns)

def bootstrap_logit_player_effects(
    X, y, n_boot=2000, C=1.0, penalty="l2", solver="liblinear", random_state=42
):
    """
    Stratified bootstrap so each resample has both classes.
    Returns:
      coef_df: per-feature summary (means, 95% CI, odds ratios, P(beta>0))
      boot_mat: (n_boot x p) matrix of bootstrapped coefficients
    """
    rng = np.random.default_rng(random_state)
    model = LogisticRegression(penalty=penalty, C=C, solver=solver, max_iter=2000)

    # indices by class
    idx0 = np.where(y.values == 0)[0]
    idx1 = np.where(y.values == 1)[0]
    n0, n1 = len(idx0), len(idx1)

    if n0 == 0 or n1 == 0:
        raise ValueError("Your original dataset has only one class; cannot fit logistic regression.")

    # keep original class proportions in each bootstrap sample
    n = len(y)
    w1 = n1 / n
    n1_b = max(1, int(round(w1 * n)))
    n0_b = max(1, n - n1_b)

    p = X.shape[1]
    cols = X.columns.tolist()
    boot_mat = np.zeros((n_boot, p), dtype=float)

    b = 0
    attempts = 0
    max_attempts = n_boot * 5  # safety to avoid infinite loop

    while b < n_boot and attempts < max_attempts:
        attempts += 1
        # sample WITH replacement inside each class
        samp0 = rng.choice(idx0, size=n0_b, replace=True)
        samp1 = rng.choice(idx1, size=n1_b, replace=True)
        idx_b = np.concatenate([samp0, samp1])
        rng.shuffle(idx_b)

        Xb = X.iloc[idx_b]
        yb = y.iloc[idx_b]

        # guard: should always have both classes, but we double-check
        if yb.nunique() < 2:
            continue

        try:
            model.fit(Xb, yb)
            boot_mat[b] = model.coef_[0]
            b += 1
        except Exception:
            # very occasionally a solver hiccup; just resample
            continue

    if b < n_boot:
        print(f"Warning: only completed {b}/{n_boot} successful bootstrap fits.")

    # summary
    mean = boot_mat[:b].mean(axis=0)
    lo = np.percentile(boot_mat[:b], 2.5, axis=0)
    hi = np.percentile(boot_mat[:b], 97.5, axis=0)
    prob_pos = (boot_mat[:b] > 0).mean(axis=0)

    odds_mean = np.exp(mean)
    odds_lo = np.exp(lo)
    odds_hi = np.exp(hi)

    coef_df = pd.DataFrame({
        "feature": cols,
        "coef_mean": mean,
        "coef_lo": lo,
        "coef_hi": hi,
        "odds_ratio": odds_mean,
        "odds_lo": odds_lo,
        "odds_hi": odds_hi,
        "prob_coef_gt_0": prob_pos
    }).set_index("feature")

    return coef_df, boot_mat[:b]

def plot_forest_odds_ratios(coef_df, exclude_intercept=True, top_n=None, figsize=(8, 12)):
    df = coef_df.copy()
    if exclude_intercept and "(intercept)" in df.index:
        df = df.drop(index="(intercept)")
    df = df.sort_values("odds_ratio", ascending=False)
    if top_n:
        df = pd.concat([df.head(top_n // 2), df.tail(top_n - top_n // 2)])
    y_pos = np.arange(len(df))
    fig, ax = plt.subplots(figsize=figsize)
    ax.hlines(y=y_pos, xmin=df["odds_lo"], xmax=df["odds_hi"])
    ax.scatter(df["odds_ratio"], y_pos)
    ax.axvline(1.0, linestyle="--")
    ax.set_yticks(y_pos)
    ax.set_yticklabels(df.index)
    ax.set_xlabel("Odds ratio (exp(coef))")
    ax.set_title("Player effects on scoring odds (bootstrap 95% CI)")
    fig.tight_layout()
    plt.show()

def plot_stability_bar(coef_df, exclude_intercept=True, figsize=(10, 6)):
    df = coef_df.copy()
    if exclude_intercept and "(intercept)" in df.index:
        df = df.drop(index="(intercept)")
    df = df.sort_values("prob_coef_gt_0", ascending=True)
    fig, ax = plt.subplots(figsize=figsize)
    ax.barh(df.index, df["prob_coef_gt_0"])
    ax.set_xlim(0, 1)
    ax.set_xlabel("Share of bootstrap runs with coef > 0")
    ax.set_title("Stability of player effects")
    fig.tight_layout()
    plt.show()

def plot_boot_histograms(boot_mat, coef_df, players, bins=30, figsize=(7, 4)):
    col_to_idx = {c: i for i, c in enumerate(coef_df.index)}
    for name in players:
        if name not in col_to_idx:
            continue
        j = col_to_idx[name]
        fig, ax = plt.subplots(figsize=figsize)
        ax.hist(boot_mat[:, j], bins=bins)
        ax.axvline(0.0, linestyle="--")
        ax.set_title(f"Bootstrap distribution of coef: {name}")
        ax.set_xlabel("Log-odds coefficient")
        ax.set_ylabel("Frequency")
        fig.tight_layout()
        plt.show()

coef_df, boot_mat = bootstrap_logit_player_effects(X, y, n_boot=2000, C=5.0)
plot_forest_odds_ratios(coef_df, exclude_intercept=True, figsize=(8, 10))
plot_stability_bar(coef_df, exclude_intercept=True)
plot_boot_histograms(boot_mat, coef_df, ["09 Zajac","02 Cego","29 Ruben"])

import pymc as pm
import numpy as np
import pandas as pd
import arviz as az


player_names = X.columns.tolist()
X_mat = X.values

# --- Bayesian logistic regression ---
with pm.Model() as model:
    # Priors
    alpha = pm.Normal("alpha", mu=0, sigma=2)  # intercept
    beta = pm.Normal("beta", mu=0, sigma=1, shape=X_mat.shape[1])  # player effects

    # Linear predictor
    logits = alpha + pm.math.dot(X_mat, beta)

    # Likelihood
    y_obs = pm.Bernoulli("y_obs", logit_p=logits, observed=y)

    # Sample posterior
    trace = pm.sample(
        draws=2000, tune=1000, target_accept=0.9, random_seed=42, cores=4
    )

# --- Summarize results ---
summary = az.summary(trace, var_names=["beta"], hdi_prob=0.95)
summary["player"] = player_names
summary = summary.set_index("player")
print(summary)

# --- Plot player effects ---
az.plot_forest(trace, var_names=["beta"], combined=True, hdi_prob=0.95)

coef_df

coef_df

SB.aggregated_player_stats_df.sort_values('adjusted_offensive_gpa', ascending=False)[['player', 'adjusted_offensive_gpa']]

SB.game_player_stats_df.query('player == "02 Cego"')

SB.aggregated_player_stats_df.query('player == "13 Hartley"')

player_possessions_df = pd.merge(SB.player_points_dfs["Tchac 2025-05-30_17-24-00"], SB.possessions_dfs['Tchac 2025-05-30_17-24-00'], left_on='points_played', right_on='point', how='left')

player_possessions_df.query('player=="02 Cego"')['scoring_prob_start'].sum()

player_possessions_df.query('player=="13 Hartley"')['scoring_prob_start'].sum()

SB.player_points_dfs["Tchac 2025-05-30_17-24-00"].query('player == "13 Hartley"')

SB.game_player_stats_df.query('player == "94 Jannis"')[['player', 'game', 'total_gpa', 'total_offensive_gpa']]

SB.aggregated_player_stats_df.sort_values('total_gpa', ascending=False)

SB.aggregated_player_stats_df.sort_values('adjusted_gpa', ascending=False)

SB.plot_turnovers(draw_arrows=False)

SB.plot_passes(draw_arrows=False)

SB

# plot the thrower_gpa on y and receiver_gpa on x
# labeling each player and with a diagonal line
fig, ax = plt.subplots(figsize=(10, 10))

ax.scatter(SB.aggregated_player_stats_df['adjusted_thrower_gpa'], SB.aggregated_player_stats_df['adjusted_receiver_gpa'])
for i, txt in enumerate(SB.aggregated_player_stats_df['player']):
    ax.annotate(txt, (SB.aggregated_player_stats_df['adjusted_thrower_gpa'][i] + 0.001, SB.aggregated_player_stats_df['adjusted_receiver_gpa'][i] + 0.001))
# plot the diagonal and the 0 lines, using the graph min and max values
min_throwing = min(SB.aggregated_player_stats_df['adjusted_thrower_gpa'])
min_receiving = min(SB.aggregated_player_stats_df['adjusted_receiver_gpa'])
max_throwing = max(SB.aggregated_player_stats_df['adjusted_thrower_gpa'])
max_receiving = max(SB.aggregated_player_stats_df['adjusted_receiver_gpa'])
ax.plot([0, 0], [min_receiving, max_receiving], 'k--')
ax.plot([min_throwing, max_throwing], [0, 0], 'k--')

ax.set_xlabel('Thrower GPA')
ax.set_ylabel('Receiver GPA')

SB.aggregated_player_stats_df

# plot turns per throwing gpa
fig, ax = plt.subplots(figsize=(10, 10))

team_mean = SB.aggregated_player_stats_df['thrower_gpa_no_turns'].mean()/SB.aggregated_player_stats_df['turnover_thrown'].mean()
ax.scatter(SB.aggregated_player_stats_df['turnover_thrown'], SB.aggregated_player_stats_df['thrower_gpa_no_turns'])
for i, txt in enumerate(SB.aggregated_player_stats_df['player']):
    ax.annotate(txt, (SB.aggregated_player_stats_df['turnover_thrown'][i] + 0.001, SB.aggregated_player_stats_df['thrower_gpa_no_turns'][i] + 0.001))

# plot a dotted line at the slope of the team mean
turnover_range = [0, SB.aggregated_player_stats_df['turnover_thrown'].max()]
ax.plot(turnover_range, [team_mean*x for x in turnover_range], 'k--')

ax.set_xlabel('Turnovers')
ax.set_ylabel('Thrower GPA (No Turns)')

# plot turns per throwing gpa
fig, ax = plt.subplots(figsize=(10, 10))

team_mean = SB.aggregated_player_stats_df['total_offensive_gpa_no_turns'].mean()/SB.aggregated_player_stats_df['total_turnovers'].mean()
ax.scatter(SB.aggregated_player_stats_df['total_turnovers'], SB.aggregated_player_stats_df['total_offensive_gpa_no_turns'])
for i, txt in enumerate(SB.aggregated_player_stats_df['player']):
    ax.annotate(txt, (SB.aggregated_player_stats_df['total_turnovers'][i] + 0.001, SB.aggregated_player_stats_df['total_offensive_gpa_no_turns'][i] + 0.001))

# plot a dotted line at the slope of the team mean
turnover_range = [0, SB.aggregated_player_stats_df['total_turnovers'].max()]
ax.plot(turnover_range, [team_mean*x for x in turnover_range], 'k--')

ax.set_xlabel('Turnovers')
ax.set_ylabel('Total Offensive GPA (No Turns)')

fig, ax = plt.subplots(figsize=(10, 10))

team_mean = SB.aggregated_player_stats_df['receiver_gpa_no_turns'].mean()/SB.aggregated_player_stats_df['total_turnovers'].mean()
ax.scatter(SB.aggregated_player_stats_df['total_turnovers'], SB.aggregated_player_stats_df['receiver_gpa_no_turns'])
for i, txt in enumerate(SB.aggregated_player_stats_df['player']):
    ax.annotate(txt, (SB.aggregated_player_stats_df['total_turnovers'][i] + 0.001, SB.aggregated_player_stats_df['receiver_gpa_no_turns'][i] + 0.001))

# plot a dotted line at the slope of the team mean
turnover_range = [0, SB.aggregated_player_stats_df['total_turnovers'].max()]
ax.plot(turnover_range, [team_mean*x for x in turnover_range], 'k--')

ax.set_xlabel('Turnovers')
ax.set_ylabel('Receiver GPA (No Turns)')

SB.aggregated_player_stats_df['meters_gained_per_catch'] = SB.aggregated_player_stats_df['receiving_meters_gained']/SB.aggregated_player_stats_df['catches']
SB.aggregated_player_stats_df.sort_values(['meters_gained_per_catch'], ascending=False)[['player', 'meters_gained_per_catch']]

SB.aggregated_player_stats_df['centering_meters_gained_per_catch'] = SB.aggregated_player_stats_df['receiving_centering_meters_gained']/SB.aggregated_player_stats_df['catches']
SB.aggregated_player_stats_df.sort_values(['centering_meters_gained_per_catch'], ascending=False)[['player', 'centering_meters_gained_per_catch']]

SB.aggregated_player_stats_df['reciever_gpa_per_catch'] = SB.aggregated_player_stats_df['receiver_gpa']/SB.aggregated_player_stats_df['catches']
SB.aggregated_player_stats_df.sort_values(['reciever_gpa_per_catch'], ascending=False)[['player', 'reciever_gpa_per_catch']]

SB.player_stats_dfs['Heidees 2025-05-18_20-38-33'].loc[SB.player_stats_dfs['Heidees 2025-05-18_20-38-33']['player']=='02 Cego']

SB.aggregated_player_stats_df.to_csv(os.path.join('/content/drive/MyDrive', os.path.join(DATA_DIRECTORY, 'processed'), 'pre_eucf.csv'))

SB.aggregated_player_stats_df

all_passes_df = pd.DataFrame()
for game_id in GAMES.keys():
  passes = SB.passes_dfs[game_id]
  passes['game'] = GAMES[game_id]
  all_passes_df = pd.concat([passes, all_passes_df])

all_passes_df.query("receiver == '94 Jannis'").query("receiver_error == 1")[['game', 'point', 'possession', 'thrower', 'receiver']]

all_passes_df.query("thrower == '13 Hartley'").query("thrower_error == 1")[['game', 'point', 'possession', 'thrower', 'receiver']]

# bucket the dist_from_sideline_start and then plot the turnover rate
all_passes_df['dist_from_sideline_start_bin'] = pd.cut(all_passes_df['dist_from_sideline_start'], bins=5)
turns = all_passes_df.groupby('dist_from_sideline_start_bin')['turnover'].mean()
#plot the results
sns.barplot(x=turns.index, y=turns.values)
plt.ylabel('Turnover Rate')
plt.xlabel('Distance from Sideline (m)')
plt.title('Turnover Rate by Distance from Sideline')
# rotate x ticks
plt.xticks(rotation=45)
plt.show()

all_passes_df['gpa_no_turns'] = all_passes_df.apply(lambda x: x['gpa'] if x['turnover']==0 else (x['gpa'] + x['game_efficiency']), axis=1)
#
all_passes_df['dist_from_sideline_start_bin'] = pd.cut(all_passes_df['dist_from_sideline_start'], bins=5)
turns = all_passes_df.groupby('dist_from_sideline_start_bin')['gpa_no_turns'].mean()
#plot the results
sns.barplot(x=turns.index, y=turns.values)
plt.ylabel('GPA (no turns)')
plt.xlabel('Distance from Sideline (m)')
plt.title('GPA (no turns) by Distance from Sideline')
# rotate x ticks
plt.xticks(rotation=45)
plt.show()

all_passes_df['dist_from_sideline_start_bin'] = pd.cut(all_passes_df['dist_from_sideline_start'], bins=5)
turns = all_passes_df.groupby('dist_from_sideline_start_bin')['gpa'].mean()
#plot the results
sns.barplot(x=turns.index, y=turns.values)
plt.ylabel('GPA')
plt.xlabel('Distance from Sideline (m)')
plt.title('GPA by Distance from Sideline')
# rotate x ticks
plt.xticks(rotation=45)
plt.show()

all_passes_df['dist_from_sideline_start_bin'] = pd.cut(all_passes_df['dist_from_sideline_start'], bins=5)
turns = all_passes_df.groupby('dist_from_sideline_start_bin')['gpa'].count()
#plot the results
sns.barplot(x=turns.index, y=turns.values)
plt.ylabel('GPA')
plt.xlabel('Distance from Sideline (m)')
plt.title('Pass Count by Distance from Sideline')
# rotate x ticks
plt.xticks(rotation=45)
plt.show()

all_passes_df['dist_from_sideline_start_bin'] = pd.cut(all_passes_df['dist_from_sideline_start'], bins=5)
turns = all_passes_df.groupby('dist_from_sideline_start_bin')['dist_to_endzone_diff'].mean()
#plot the results
sns.barplot(x=turns.index, y=turns.values)
plt.ylabel('Average Vertical Gain')
plt.xlabel('Distance from Sideline (m)')
plt.title('Average Vertical Gain by Distance from Sideline')
# rotate x ticks
plt.xticks(rotation=45)
plt.show()

SB.plot_turnovers(draw_arrows=False)

"""

>
D-Line Handler Analysis
"""

all_passes_df.query('possession > 1')

all_possessions_df = pd.DataFrame()
for game_id in GAMES.keys():
  game_possessions = SB.possessions_dfs[game_id]
  game_possessions['game'] = GAMES[game_id]
  all_possessions_df = pd.concat([game_possessions, all_possessions_df])

all_passes_df = pd.DataFrame()
for game_id in GAMES.keys():
  all_passes_df = pd.concat([SB.passes_dfs[game_id], all_passes_df])

possessions = all_possessions_df[[
    'game',
    'point',
    'possession',
    'started_point_on_offense',
    'dist_to_endzone_start',
    'dist_from_middle_start',
    'start_x_m'
]]

pass_poss = all_passes_df.merge(possessions, on=['game','point','possession'], suffixes=('', '_poss'))

pass_poss['pass_number'] = pass_poss.groupby(['game', 'point', 'possession']).cumcount() + 1

pass_poss['starting_point'] = pass_poss['dist_to_endzone_start'].apply(lambda x: "our_half" if x > 36 else "their_half")
pass_poss['abs_x_m_from_start'] = abs(pass_poss['start_x_m'] - pass_poss['start_x_m_poss'])

pass_poss['got_field_switch'] = (pass_poss['dist_from_middle_start_poss'] > 5).astype(int) & (pass_poss['abs_x_m_from_start'] > 17).astype(int)
pass_poss['got_field_switch_first_2'] = ((pass_poss['got_field_switch']) & (pass_poss['pass_number'] <= 3)).astype(int)

pass_poss['got_gainer'] = (pass_poss['forward_distance_(m)'] > 7) & (pass_poss['turnover']==0)
pass_poss['got_gainer_first_2'] = ((pass_poss['got_gainer']) & (pass_poss['pass_number'] <= 3)).astype(int)

pass_poss['gainer_or_field_switch'] = (pass_poss['got_gainer_first_2'] + pass_poss['got_field_switch_first_2'] + pass_poss['assist']).clip(upper=1)
poss_level = pass_poss.groupby(['point', 'possession', 'game'])['gainer_or_field_switch'].max().reset_index().rename(columns={'gainer_or_field_switch': 'gainer_or_field_switch_poss'})
pass_poss = pass_poss.merge(poss_level, on=['point', 'possession', 'game'])

d_possessions = pass_poss.query('started_point_on_offense == 0')
good_d_possessions = pass_poss.query('started_point_on_offense == 0').query('gainer_or_field_switch_poss == 1')

first_two_touches = d_possessions.query('pass_number <= 2')

# group by thrower get sum and mean of
g = first_two_touches.groupby(['thrower', 'starting_point'])
results = g.agg({'gainer_or_field_switch_poss': ['sum', 'mean']})

results.sort_values(['starting_point', ('gainer_or_field_switch_poss', 'sum')], ascending=False)

